dist: xenial
sudo: required
addons:
  snaps:
    - name: crystal
      confinement: classic
      channel: latest/edge

before_install:
  - sudo apt-get install gcc pkg-config git tzdata libpcre3-dev libevent-dev libyaml-dev libgmp-dev libssl-dev libxml2-dev

before_script:
  - crystal --version
  - shards --version
  - shards install

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: crest
  local_dir: docs
  on:
    branch: master
