dist: xenial
language: crystal
crystal:
  - latest
  - nightly

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: crest
  local_dir: docs
  on:
    branch: master
