os: linux
dist: xenial
language: crystal
crystal:
  - latest
  - nightly

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
  - crystal docs

jobs:
  allow_failures:
  - crystal: nightly

deploy:
  provider: pages
  strategy: git
  cleanup: true
  token: $GITHUB_TOKEN
  project_name: crest
  local_dir: docs
  on:
    branch: master
